### ISSUE TITLE
Possibly incorrect EOS?

### ISSUE THREAD

**Issue by ZukaChilachava** [2U1/Molmo-Finetune#1]
https://github.com/2U1/Molmo-Finetune/blob/master/src/training/data.py line 113

```python
all_input_ids = [torch.tensor([151643])] # bos token id = eos token id
```

I'm probably wrong but, shouldn't the EOS be taken from the tokenizer, the index that is set there is outside the vocab range as well. could also be common practice that i'm not aware of.

**Comment by 2U1** [comment]
The id of eos_token is 151643
If you deocde the tensor into a text then it is `<|endoftext|>`
You could test like this `processor.tokenizer.decode(torch.tensor([151643]))`

**Comment by ZukaChilachava** [comment]
<img width="921" alt="Screenshot 2024-10-02 at 3 07 43 PM" src="https://github.com/user-attachments/assets/41f3d8cf-8e6e-4384-a439-3d50b6428279">

Turns out 7B O and D have different vocabs, that's why I was getting different results.

**Comment by 2U1** [comment]
@ZukaChilachava Oh, Sorry for the issue. I'll fix it.

**Comment by 2U1** [comment]
@ZukaChilachava I've fixed the eos_token_id to use from the processor.
I'm sorry for the inconvinience. You could now properly use the code.

**Comment by ZukaChilachava** [comment]
Thanks for the response!
