### ISSUE TITLE
Data Format For Point Task

### ISSUE THREAD

**Issue by caichuang0415** [2U1/Molmo-Finetune#10]
Thank you for your finetuning code and the example json data。
Could you please also provide a example json data file of finetune molmo for pointing target? Like the official paper says, molmo can generate coordinates of points according to input text, in format like : "Point to XXXX".  But I don't know the corresponding format of finetune json file.   
I would really appreciate it if you could give a example.

**Comment by 2U1** [comment]
Well the data isn't opened and, I'm not sure how the molmo points out the target. It seems like it answers in a html format. So you could make a dataset by yourself. 
The conversations should be like "user: <image>\nPoint out the persons head", "Assistant: <html>...<html>".

**Comment by caichuang0415** [comment]
Thanks for your replay, I will try it like you said.
