### ISSUE TITLE
关于self.processor保存报错

### ISSUE THREAD

**Issue by Algabeno** [2U1/Molmo-Finetune#3]
您好，我在训练时保存的时候遇到了下面的报错

`
if self.processor is not None:
   self.processor.save_pretrained(output_dir)`

/
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/autodl-tmp/autodl-tmp/Molmo-Finetune/src/training/train.py", line 213, in <module>
[rank0]:     train()
[rank0]:   File "/root/autodl-tmp/autodl-tmp/Molmo-Finetune/src/training/train.py", line 188, in train
[rank0]:     trainer.train()
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/trainer.py", line 2467, in _inner_training_loop
[rank0]:     self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/trainer.py", line 2918, in _maybe_log_save_evaluate
[rank0]:     self._save_checkpoint(model, trial, metrics=metrics)
[rank0]:   File "/root/autodl-tmp/autodl-tmp/Molmo-Finetune/src/training/trainer.py", line 160, in _save_checkpoint
[rank0]:     self.save_model(output_dir, _internal_call=True)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/trainer.py", line 3610, in save_model
[rank0]:     self._save(output_dir, state_dict=state_dict)
[rank0]:   File "/root/autodl-tmp/autodl-tmp/Molmo-Finetune/src/training/trainer.py", line 242, in _save
[rank0]:     self.processor.save_pretrained(output_dir)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/processing_utils.py", line 507, in save_pretrained
[rank0]:     attribute.save_pretrained(save_directory)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2639, in save_pretrained
[rank0]:     out_str = json.dumps(tokenizer_config, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/__init__.py", line 238, in dumps
[rank0]:     **kw).encode(obj)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/encoder.py", line 201, in encode
[rank0]:     chunks = list(chunks)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/encoder.py", line 431, in _iterencode
[rank0]:     yield from _iterencode_dict(o, _current_indent_level)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
[rank0]:     yield from chunks
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/encoder.py", line 438, in _iterencode
[rank0]:     o = _default(o)
[rank0]:   File "/root/miniconda3/envs/molmo/lib/python3.10/json/encoder.py", line 179, in default
[rank0]:     raise TypeError(f'Object of type {o.__class__.__name__} '
[rank0]: TypeError: Object of type dtype is not JSON serializable

**Comment by 2U1** [comment]
Sorry, I've fixed the bug. I forgot remove the unneccary part of the code.
Now it should work.

**Comment by Algabeno** [comment]
Thanks for the response!
